# Run `brew bundle`

brew "direnv"
brew "git"
brew "grc"
brew "node"
brew "sshuttle"
brew "wget"

# completions
brew "bash-completion"
brew "bash-git-prompt"
brew "launchctl-completion"
brew "open-completion"
