# Run `brew bundle`

brew "bash" # echo /usr/local/bin/bash >> /etc/shells && chsh -s /usr/local/bin/bash
brew "direnv"
brew "git"
brew "grc"
brew "node"
brew "sshuttle"
brew "wget"

# completions
brew "bash-completion@2"
brew "bash-git-prompt"
brew "launchctl-completion"
brew "open-completion"

# add rmtree command
tap "beeftornado/rmtree"
